-- ThunderID schema update: control plane configdb (PostgreSQL)
--
-- Brings an existing database up to this release. No table is dropped and no row is touched: new
-- tables are created, and existing tables keep their data while their keys are widened in place.
--
-- The only change to a table that already exists is its constraints. Replacing a primary key means
-- dropping the old constraint and adding the new one; the table and its rows stay where they are.
--
--   old   PRIMARY KEY (ID)
--   new   PRIMARY KEY (DEPLOYMENT_ID, ID)
--
-- That is what lets one database hold more than one deployment: the same id may exist in two of them
-- without colliding. Foreign keys pointing at those tables are widened to match.
--
-- Safe to run again: constraint drops are conditional and every CREATE is IF NOT EXISTS.

BEGIN;

-- ------------------------------------------------------------------ new tables
CREATE TABLE IF NOT EXISTS "DATA_PLANE_JOB" (
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    ID            VARCHAR(64)  NOT NULL,
    -- The deployment this is for, as "<org>:<env>". DEPLOYMENT_ID above is the organization, so that
    -- an organization's queue sits in one partition with its gateways.
    DATA_PLANE_ID VARCHAR(255) NOT NULL,
    GATEWAY_ID        VARCHAR(64),
    -- What to do: "import" applies configuration, "secret_put" stores one credential.
    TYPE          VARCHAR(32)  NOT NULL,
    -- The request, as JSON. Encrypted when it carries a credential, which is what ENCRYPTED records:
    -- a secret is held here only until it is delivered, and never in the clear.
    PAYLOAD       TEXT         NOT NULL,
    ENCRYPTED     CHAR(1)      DEFAULT '0' NOT NULL,
    -- pending -> claimed -> done | failed.
    STATUS        VARCHAR(16)  NOT NULL,
    -- Which pod is delivering it, for diagnosing a job stuck in claimed.
    CLAIMED_BY    VARCHAR(255),
    -- What the Data Plane answered, as JSON, or why it could not be delivered.
    RESULT        TEXT,
    ERROR         TEXT,
    ATTEMPTS      INTEGER      DEFAULT 0 NOT NULL,
    CREATED_AT    TIMESTAMPTZ  DEFAULT NOW(),
    UPDATED_AT    TIMESTAMPTZ  DEFAULT NOW(),
    COMPLETED_AT  TIMESTAMPTZ,
    PRIMARY KEY (DEPLOYMENT_ID, ID)
);
CREATE INDEX IF NOT EXISTS idx_data_plane_job_queue ON "DATA_PLANE_JOB" (DATA_PLANE_ID, STATUS, CREATED_AT);

CREATE TABLE IF NOT EXISTS "DATA_PLANE_TOKEN" (
    DATA_PLANE_ID VARCHAR(255) PRIMARY KEY,
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    TOKEN         TEXT         NOT NULL,
    CREATED_AT    TIMESTAMPTZ  DEFAULT NOW(),
    UPDATED_AT    TIMESTAMPTZ  DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_data_plane_token_deployment ON "DATA_PLANE_TOKEN" (DEPLOYMENT_ID);

CREATE TABLE IF NOT EXISTS "GATEWAY" (
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    ID            VARCHAR(36)  NOT NULL,
    DATA          TEXT         NOT NULL,
    CREATED_AT    TIMESTAMPTZ  DEFAULT NOW(),
    UPDATED_AT    TIMESTAMPTZ  DEFAULT NOW(),
    PRIMARY KEY (DEPLOYMENT_ID, ID)
);

CREATE TABLE IF NOT EXISTS "GATEWAY_APPLY" (
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    GATEWAY_ID    VARCHAR(36)  NOT NULL,
    ORDINAL       INTEGER      NOT NULL,
    SEQ           INTEGER      NOT NULL,
    APPLIED_AT    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (DEPLOYMENT_ID, GATEWAY_ID, ORDINAL),
    CONSTRAINT fk_gateway_apply_gateway
        FOREIGN KEY (DEPLOYMENT_ID, GATEWAY_ID) REFERENCES "GATEWAY" (DEPLOYMENT_ID, ID)
        ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_gateway_apply_gateway ON "GATEWAY_APPLY" (DEPLOYMENT_ID, GATEWAY_ID);

CREATE TABLE IF NOT EXISTS "GATEWAY_VARIABLE" (
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    ID            VARCHAR(36)  PRIMARY KEY,
    GATEWAY_ID        VARCHAR(36)  NOT NULL,
    KEY           VARCHAR(255) NOT NULL,
    VALUE         TEXT         NOT NULL,
    DESCRIPTION   VARCHAR(255),
    CREATED_AT    TIMESTAMPTZ  DEFAULT NOW(),
    UPDATED_AT    TIMESTAMPTZ  DEFAULT NOW(),
    CONSTRAINT unique_gateway_variable_key UNIQUE (DEPLOYMENT_ID, GATEWAY_ID, KEY),
    CONSTRAINT fk_gateway_variable_gateway
        FOREIGN KEY (DEPLOYMENT_ID, GATEWAY_ID) REFERENCES "GATEWAY" (DEPLOYMENT_ID, ID)
        ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_gateway_variable_gateway ON "GATEWAY_VARIABLE" (DEPLOYMENT_ID, GATEWAY_ID);

CREATE TABLE IF NOT EXISTS "MANAGED_RESOURCE" (
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    RESOURCE_TYPE VARCHAR(64)  NOT NULL,
    RESOURCE_ID   VARCHAR(255) NOT NULL,
    CREATED_AT    TIMESTAMPTZ  DEFAULT NOW(),
    PRIMARY KEY (DEPLOYMENT_ID, RESOURCE_TYPE, RESOURCE_ID)
);
CREATE INDEX IF NOT EXISTS idx_managed_resource_deployment ON "MANAGED_RESOURCE" (DEPLOYMENT_ID);

CREATE TABLE IF NOT EXISTS "PARAMETERISED_RESOURCE" (
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    ID            VARCHAR(36)  PRIMARY KEY,
    RESOURCE_TYPE VARCHAR(64)  NOT NULL,
    NAME          VARCHAR(255) NOT NULL,
    PAYLOAD       JSONB        NOT NULL,
    CREATED_AT    TIMESTAMPTZ  DEFAULT NOW(),
    UPDATED_AT    TIMESTAMPTZ  DEFAULT NOW(),
    CONSTRAINT unique_parameterised_resource UNIQUE (DEPLOYMENT_ID, RESOURCE_TYPE, NAME)
);
CREATE INDEX IF NOT EXISTS idx_parameterised_resource_deployment ON "PARAMETERISED_RESOURCE" (DEPLOYMENT_ID, RESOURCE_TYPE, NAME);

CREATE TABLE IF NOT EXISTS "SECRET" (
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    ID            VARCHAR(36)  PRIMARY KEY,
    NAME          VARCHAR(255) NOT NULL,
    KIND          VARCHAR(10)  NOT NULL CHECK (KIND IN ('hash', 'value')),
    VALUE         TEXT         NOT NULL,
    ALGORITHM     VARCHAR(50),
    PARAMETERS    TEXT,
    DESCRIPTION   VARCHAR(255),
    CREATED_AT    TIMESTAMPTZ  DEFAULT NOW(),
    UPDATED_AT    TIMESTAMPTZ  DEFAULT NOW(),
    CONSTRAINT unique_secret_name UNIQUE (DEPLOYMENT_ID, NAME)
);
CREATE INDEX IF NOT EXISTS idx_secret_deployment ON "SECRET" (DEPLOYMENT_ID);

CREATE TABLE IF NOT EXISTS "TENANT" (
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    ID            VARCHAR(36)  PRIMARY KEY,
    TENANT_ID     VARCHAR(255) NOT NULL,
    NAME          VARCHAR(255),
    CREATED_AT    TIMESTAMPTZ  DEFAULT NOW(),
    UPDATED_AT    TIMESTAMPTZ  DEFAULT NOW(),
    CONSTRAINT unique_tenant_id UNIQUE (DEPLOYMENT_ID, TENANT_ID)
);
CREATE INDEX IF NOT EXISTS idx_tenant_deployment ON "TENANT" (DEPLOYMENT_ID);

CREATE TABLE IF NOT EXISTS "VERSION" (
    DEPLOYMENT_ID VARCHAR(255) NOT NULL,
    SEQ           INTEGER      NOT NULL,
    DATA          TEXT         NOT NULL,
    CREATED_AT    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (DEPLOYMENT_ID, SEQ)
);

-- ------------------------------------------ keys widened on existing tables
-- Constraint names are looked up rather than assumed: a database created by an older script may
-- carry system-generated names that a fresh install would not produce.
CREATE OR REPLACE FUNCTION pg_temp.drop_con(tbl text, kind char) RETURNS void AS $$
DECLARE c text;
BEGIN
  FOR c IN SELECT conname FROM pg_constraint
           WHERE conrelid = format('%I', tbl)::regclass AND contype = kind
  LOOP EXECUTE format('ALTER TABLE %I DROP CONSTRAINT %I', tbl, c); END LOOP;
END $$ LANGUAGE plpgsql;

-- Foreign keys come off first: they depend on the primary keys about to be replaced.
SELECT pg_temp.drop_con('ACTION', 'f');
SELECT pg_temp.drop_con('CERTIFICATE', 'f');
SELECT pg_temp.drop_con('CREDENTIAL_CONFIGURATION', 'f');
SELECT pg_temp.drop_con('ENTITY_TYPES', 'f');
SELECT pg_temp.drop_con('FLOW', 'f');
SELECT pg_temp.drop_con('FLOW_VERSION', 'f');
SELECT pg_temp.drop_con('IDP', 'f');
SELECT pg_temp.drop_con('INBOUND_CLIENT', 'f');
SELECT pg_temp.drop_con('LAYOUT', 'f');
SELECT pg_temp.drop_con('NOTIFICATION_SENDER', 'f');
SELECT pg_temp.drop_con('OAUTH_INBOUND_PROFILE', 'f');
SELECT pg_temp.drop_con('PRESENTATION_DEFINITION', 'f');
SELECT pg_temp.drop_con('RESOURCE', 'f');
SELECT pg_temp.drop_con('RESOURCE_SERVER', 'f');
SELECT pg_temp.drop_con('ROLE', 'f');
SELECT pg_temp.drop_con('ROLE_PERMISSION', 'f');
SELECT pg_temp.drop_con('THEME', 'f');

SELECT pg_temp.drop_con('ACTION', 'p');
ALTER TABLE "ACTION" ALTER COLUMN DEPLOYMENT_ID SET NOT NULL;
ALTER TABLE "ACTION" ADD PRIMARY KEY (DEPLOYMENT_ID, ID);
SELECT pg_temp.drop_con('CERTIFICATE', 'p');
ALTER TABLE "CERTIFICATE" ALTER COLUMN DEPLOYMENT_ID SET NOT NULL;
ALTER TABLE "CERTIFICATE" ADD PRIMARY KEY (DEPLOYMENT_ID, ID);
SELECT pg_temp.drop_con('CREDENTIAL_CONFIGURATION', 'p');
ALTER TABLE "CREDENTIAL_CONFIGURATION" ALTER COLUMN DEPLOYMENT_ID SET NOT NULL;
ALTER TABLE "CREDENTIAL_CONFIGURATION" ADD PRIMARY KEY (DEPLOYMENT_ID, ID);
SELECT pg_temp.drop_con('ENTITY_TYPES', 'p');
ALTER TABLE "ENTITY_TYPES" ALTER COLUMN DEPLOYMENT_ID SET NOT NULL;
ALTER TABLE "ENTITY_TYPES" ADD PRIMARY KEY (DEPLOYMENT_ID, ID);
SELECT pg_temp.drop_con('FLOW', 'p');
ALTER TABLE "FLOW" ALTER COLUMN DEPLOYMENT_ID SET NOT NULL;
ALTER TABLE "FLOW" ADD PRIMARY KEY (DEPLOYMENT_ID, ID);
SELECT pg_temp.drop_con('FLOW_VERSION', 'p');
ALTER TABLE "FLOW_VERSION" ALTER COLUMN DEPLOYMENT_ID SET NOT NULL;
ALTER TABLE "FLOW_VERSION" ADD PRIMARY KEY (FLOW_ID, VERSION, DEPLOYMENT_ID);
SELECT pg_temp.drop_con('IDP', 'p');
ALTER TABLE "IDP" ALTER COLUMN DEPLOYMENT_ID SET NOT NULL;
ALTER TABLE "IDP" ADD PRIMARY KEY (DEPLOYMENT_ID, ID);
SELECT pg_temp.drop_con('INBOUND_CLIENT', 'p');
ALTER TABLE "INBOUND_CLIENT" ALTER COLUMN DEPLOYMENT_ID SET NOT NULL;
ALTER TABLE "INBOUND_CLIENT" ADD PRIMARY KEY (DEPLOYMENT_ID, ENTITY_ID);
SELECT pg_temp.drop_con('LAYOUT', 'p');
ALTER TABLE "LAYOUT" ALTER COLUMN DEPLOYMENT_ID SET NOT NULL;
ALTER TABLE "LAYOUT" ADD PRIMARY KEY (DEPLOYMENT_ID, ID);
SELECT pg_temp.drop_con('NOTIFICATION_SENDER', 'p');
ALTER TABLE "NOTIFICATION_SENDER" ALTER COLUMN DEPLOYMENT_ID SET NOT NULL;
ALTER TABLE "NOTIFICATION_SENDER" ADD PRIMARY KEY (DEPLOYMENT_ID, ID);
SELECT pg_temp.drop_con('OAUTH_INBOUND_PROFILE', 'p');
ALTER TABLE "OAUTH_INBOUND_PROFILE" ALTER COLUMN DEPLOYMENT_ID SET NOT NULL;
ALTER TABLE "OAUTH_INBOUND_PROFILE" ADD PRIMARY KEY (ENTITY_ID, DEPLOYMENT_ID);
SELECT pg_temp.drop_con('PRESENTATION_DEFINITION', 'p');
ALTER TABLE "PRESENTATION_DEFINITION" ALTER COLUMN DEPLOYMENT_ID SET NOT NULL;
ALTER TABLE "PRESENTATION_DEFINITION" ADD PRIMARY KEY (DEPLOYMENT_ID, ID);
SELECT pg_temp.drop_con('RESOURCE', 'p');
ALTER TABLE "RESOURCE" ALTER COLUMN DEPLOYMENT_ID SET NOT NULL;
ALTER TABLE "RESOURCE" ADD PRIMARY KEY (DEPLOYMENT_ID, ID);
SELECT pg_temp.drop_con('RESOURCE_SERVER', 'p');
ALTER TABLE "RESOURCE_SERVER" ALTER COLUMN DEPLOYMENT_ID SET NOT NULL;
ALTER TABLE "RESOURCE_SERVER" ADD PRIMARY KEY (DEPLOYMENT_ID, ID);
SELECT pg_temp.drop_con('ROLE', 'p');
ALTER TABLE "ROLE" ALTER COLUMN DEPLOYMENT_ID SET NOT NULL;
ALTER TABLE "ROLE" ADD PRIMARY KEY (DEPLOYMENT_ID, ID);
SELECT pg_temp.drop_con('ROLE_PERMISSION', 'p');
ALTER TABLE "ROLE_PERMISSION" ALTER COLUMN DEPLOYMENT_ID SET NOT NULL;
ALTER TABLE "ROLE_PERMISSION" ADD PRIMARY KEY (ROLE_ID, DEPLOYMENT_ID, RESOURCE_SERVER_ID, PERMISSION);
SELECT pg_temp.drop_con('THEME', 'p');
ALTER TABLE "THEME" ALTER COLUMN DEPLOYMENT_ID SET NOT NULL;
ALTER TABLE "THEME" ADD PRIMARY KEY (DEPLOYMENT_ID, ID);

-- Foreign keys restored, now referencing the widened primary keys.
ALTER TABLE "ACTION" ADD FOREIGN KEY (DEPLOYMENT_ID, RESOURCE_SERVER_ID) REFERENCES "RESOURCE_SERVER" (DEPLOYMENT_ID, ID) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ACTION" ADD FOREIGN KEY (DEPLOYMENT_ID, RESOURCE_ID) REFERENCES "RESOURCE" (DEPLOYMENT_ID, ID) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "FLOW_VERSION" ADD FOREIGN KEY (DEPLOYMENT_ID, FLOW_ID) REFERENCES "FLOW" (DEPLOYMENT_ID, ID) ON DELETE CASCADE;
ALTER TABLE "OAUTH_INBOUND_PROFILE" ADD FOREIGN KEY (DEPLOYMENT_ID, ENTITY_ID) REFERENCES "INBOUND_CLIENT" (DEPLOYMENT_ID, ENTITY_ID) ON DELETE CASCADE;
ALTER TABLE "RESOURCE" ADD FOREIGN KEY (DEPLOYMENT_ID, RESOURCE_SERVER_ID) REFERENCES "RESOURCE_SERVER" (DEPLOYMENT_ID, ID) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "RESOURCE" ADD FOREIGN KEY (DEPLOYMENT_ID, PARENT_RESOURCE_ID) REFERENCES "RESOURCE" (DEPLOYMENT_ID, ID) ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ROLE_PERMISSION" ADD FOREIGN KEY (DEPLOYMENT_ID, ROLE_ID) REFERENCES "ROLE" (DEPLOYMENT_ID, ID) ON DELETE CASCADE;

COMMIT;
